spring.application.name=clientes

# Conexión a PostgreSQL (cambia la contraseña si pusiste otra al instalar)
spring.datasource.url=jdbc:postgresql://localhost:5432/clientes_db
spring.datasource.username=postgres
spring.datasource.password=Ederjesus_0805

# Spring crea y actualiza la tabla sola
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false